# Generated by Django 4.1.2 on 2022-10-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('poster', models.URLField()),
                ('url', models.URLField()),
                ('content', models.TextField(max_length=255)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Aventure', 'Aventure'), ('Comedie', 'Comedie'), ('Drame', 'Drame'), ('Fantastique', 'Fantastique'), ('Horreur', 'Horreur'), ('Policier', 'Policier'), ('Science-fiction', 'Science-fiction'), ('Thriller', 'Thriller')], max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
